import { apiFetch } from '../../services/apiUrl.js'
import { useCallback, useEffect, useState } from 'react'
import { BadgeCheck, FileText, RefreshCw, Upload } from 'lucide-react'

const cls='w-full rounded-xl bg-slate-950 border border-slate-700 px-3 py-2.5 text-sm text-slate-100 outline-none focus:border-amber-500'
const token=()=>localStorage.getItem('mineguard_jwt_token')||''
const expiryLabel=d=>d<0?`Expired ${Math.abs(d)} day${Math.abs(d)===1?'':'s'} ago`:d===0?'Expires today':`${d} day${d===1?'':'s'} left`
export default function LabourDocuments({supervisor=false}) {
  const [documents,setDocuments]=useState([]),[summary,setSummary]=useState({}),[storageAvailable,setStorageAvailable]=useState(true),[loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
  const [form,setForm]=useState({docType:'',regCode:'',issueDate:'',expiryDate:''}),[file,setFile]=useState(null)
  const load=useCallback(async()=>{setLoading(true);setError('');try{const res=await apiFetch(supervisor?'/api/supervisor/documents':'/api/labour/documents',{headers:{Authorization:`Bearer ${token()}`}});const data=await res.json();if(!res.ok)throw new Error(data.message||'Could not load documents');setDocuments(data.documents||[]);setSummary(data.summary||{});setStorageAvailable(data.storageAvailable!==false)}catch(e){setError(e.message)}finally{setLoading(false)}},[supervisor])
  useEffect(()=>{load()},[load])
  const submit=async e=>{e.preventDefault();setError('');setMessage('');let attachment;if(file){attachment=await new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('Could not read selected file.'));r.onload=()=>resolve({name:file.name,mimeType:file.type,data:String(r.result).split(',')[1]});r.readAsDataURL(file)})}try{const res=await apiFetch('/api/labour/documents',{method:'POST',headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:JSON.stringify({...form,file:attachment})});const data=await res.json();if(!res.ok)throw new Error(data.message||'Upload failed');setMessage('Document submitted. It will show as pending until a supervisor verifies it.');setForm({docType:'',regCode:'',issueDate:'',expiryDate:''});setFile(null);e.target.reset();await load()}catch(err){setError(err.message)}}
  const review=async(doc,status)=>{const note=window.prompt(status==='VERIFIED'?'Optional verification note:':'Reason for rejecting this document:','')??'';if(status==='REJECTED'&&!note.trim())return;try{const res=await apiFetch(`/api/supervisor/documents/${doc._id}/review`,{method:'PATCH',headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:JSON.stringify({status,note})});const data=await res.json();if(!res.ok)throw new Error(data.message||'Review failed');await load()}catch(e){setError(e.message)}}
  return <div className="space-y-4 text-slate-100">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black flex items-center gap-2"><FileText className="text-amber-400"/>{supervisor?'Labour Documents & Licences':'My Documents & Licences'}</h2><p className="text-xs text-slate-400">Expiry countdowns use the document’s expiry date. Submit renewals early and keep evidence current.</p></div><button onClick={load} className="px-3 py-2 rounded-xl bg-slate-800 text-xs"><RefreshCw size={13} className={`inline mr-1 ${loading?'animate-spin':''}`}/>Refresh</button></header>
    {error&&<p className="p-3 rounded-xl border border-red-500/30 bg-red-950/40 text-xs text-red-200">{error}</p>}{message&&<p className="p-3 rounded-xl border border-emerald-500/30 bg-emerald-950/30 text-xs text-emerald-200">{message}</p>}
    {!storageAvailable&&<p className="p-3 rounded-xl border border-amber-500/30 bg-amber-950/30 text-xs text-amber-200">MongoDB is offline. Stored licence records are unavailable, and new document uploads are disabled until database connectivity returns.</p>}
    {supervisor&&<div className="grid grid-cols-2 sm:grid-cols-5 gap-2">{[['Documents',summary.total],['Expired',summary.expired],['Expiring in 30 days',summary.expiringSoon],['Valid',summary.valid],['Pending review',summary.pendingReview]].map(([label,count])=><div key={label} className="rounded-xl border border-slate-800 bg-slate-900 p-3"><div className="text-[10px] text-slate-400 uppercase">{label}</div><b className="text-xl">{count??0}</b></div>)}</div>}
    {!supervisor&&<form onSubmit={submit} className="rounded-2xl border border-slate-800 bg-slate-900 p-4 grid sm:grid-cols-2 gap-2"><h3 className="sm:col-span-2 text-sm font-bold">Submit or renew a licence</h3><input className={cls} required maxLength={160} placeholder="Document / licence name" value={form.docType} onChange={e=>setForm(f=>({...f,docType:e.target.value}))}/><input className={cls} maxLength={100} placeholder="Licence / registration number" value={form.regCode} onChange={e=>setForm(f=>({...f,regCode:e.target.value}))}/><label className="text-[10px] text-slate-400">Issue date<input className={`${cls} mt-1`} type="date" value={form.issueDate} onChange={e=>setForm(f=>({...f,issueDate:e.target.value}))}/></label><label className="text-[10px] text-slate-400">Expiry date<input className={`${cls} mt-1`} type="date" required value={form.expiryDate} onChange={e=>setForm(f=>({...f,expiryDate:e.target.value}))}/></label><label className="sm:col-span-2 text-[10px] text-slate-400">Evidence file: PDF, JPEG, PNG, WebP; up to 4 MB<input className={`${cls} mt-1`} type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>{const next=e.target.files?.[0];if(next&&next.size>4*1024*1024){setError('Choose a file no larger than 4 MB.');e.target.value='';return}setFile(next||null)}}/></label><button className="sm:col-span-2 rounded-xl bg-amber-500 text-slate-950 py-2.5 font-black text-xs"><Upload size={14} className="inline mr-1"/>Submit for supervisor verification</button></form>}
    <div className="overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900"><table className="min-w-[850px] w-full text-left text-xs"><thead className="bg-slate-950/70 text-slate-400"><tr>{['Worker','Mine / Zone','Document','Licence No.','Expiry','Time left','Review status','Evidence','Action'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{documents.map(d=><tr key={d._id} className="border-t border-slate-800"><td className="p-3">{supervisor?<>{d.workerName}<span className="block text-slate-400">{d.workerId}</span></>:d.workerId}</td><td className="p-3">{d.mineId||'—'}<span className="block text-slate-400">{d.zoneId||''}</span></td><td className="p-3 font-semibold">{d.docType}</td><td className="p-3">{d.regCode||'—'}</td><td className="p-3">{new Date(d.expiryDate).toLocaleDateString()}</td><td className={`p-3 font-bold ${d.expiryStatus==='EXPIRED'?'text-red-300':d.expiryStatus==='EXPIRING_SOON'?'text-amber-300':'text-emerald-300'}`}>{expiryLabel(d.daysRemaining)}</td><td className="p-3">{d.status==='PENDING_REVIEW'?<span className="text-amber-300">Pending review</span>:d.status==='REJECTED'?<span className="text-red-300">Rejected</span>:<span className="text-emerald-300">Verified</span>}{d.verificationNote&&<span className="block text-slate-400">{d.verificationNote}</span>}</td><td className="p-3">{d.file?.data?<a className="text-sky-300" href={`data:${d.file.mimeType};base64,${d.file.data}`} download={d.file.name}>Open file</a>:<span className="text-slate-400">No scan</span>}</td><td className="p-3">{supervisor&&d._id&&!String(d._id).startsWith('qualification-')&&d.status==='PENDING_REVIEW'?<div className="flex gap-1"><button onClick={()=>review(d,'VERIFIED')} className="rounded bg-emerald-900 px-2 py-1 text-emerald-200"><BadgeCheck size={13}/></button><button onClick={()=>review(d,'REJECTED')} className="rounded bg-red-950 px-2 py-1 text-red-200">Reject</button></div>:d.source==='worker_qualification'?<span className="text-slate-400">Existing record</span>:'—'}</td></tr>)}{!documents.length&&<tr><td colSpan="9" className="p-8 text-center text-slate-400">{loading?'Loading documents…':'No documents found.'}</td></tr>}</tbody></table></div>
    {supervisor&&<p className="text-[10px] text-slate-400">Expiry is calculated from the recorded date. Confirm the physical credential and issuing authority during verification.</p>}
  </div>
}
