import { apiFetch } from '../../services/apiUrl.js'
import { useCallback, useEffect, useState } from 'react'
import { Brain, RefreshCw, ShieldAlert, TrendingUp } from 'lucide-react'

export default function LabourIncidentIntelligence(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false)
  const load=useCallback(async()=>{setLoading(true);setError('');try{const token=localStorage.getItem('mineguard_jwt_token')||'';const response=await apiFetch('/api/supervisor/labour-ai/incidents',{headers:{Authorization:`Bearer ${token}`}});const body=await response.json();if(!response.ok)throw new Error(body.message||'Could not analyze mine incident history');setData(body)}catch(e){setError(e.message)}finally{setLoading(false)}},[])
  useEffect(()=>{load()},[load])
  const score=data?.ml?.riskScore
  return <div className="p-4 sm:p-6 max-w-6xl mx-auto space-y-5 text-slate-100"><header className="flex flex-wrap justify-between items-center gap-3"><div><h2 className="text-2xl font-black flex items-center gap-2"><Brain className="text-violet-400"/>Labour Safety Intelligence</h2><p className="text-sm text-slate-400">Analysis of recorded mine incidents from the last five years.</p></div><button onClick={load} className="rounded-xl bg-slate-800 px-3 py-2 text-xs"><RefreshCw size={14} className={`inline mr-1 ${loading?'animate-spin':''}`}/>Refresh analysis</button></header>
    {error&&<div className="rounded-xl border border-amber-500/30 bg-amber-950/30 p-4 text-sm text-amber-100">{error}</div>}
    {data&&<><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Archive window','5 years'],['Mine scope',data.mineScope],['Recorded incidents',data.totalIncidents],['Last 90 days',data.recent90Days]].map(([label,value])=><div key={label} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><p className="text-[10px] uppercase tracking-wide text-slate-400">{label}</p><b className="mt-1 block text-lg">{value}</b></div>)}</div>
      <div className="grid md:grid-cols-2 gap-4"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="font-bold flex items-center gap-2"><TrendingUp size={16} className="text-amber-400"/>Historical incident pattern</h3><p className="mt-1 text-xs text-slate-400">{data.previous90Days} incidents in the preceding 90 days · Mines represented: {data.mines.join(', ')||'—'}</p><div className="mt-4 grid grid-cols-2 gap-2">{Object.entries(data.severityCounts||{}).map(([key,value])=><div key={key} className="rounded-lg bg-slate-950 p-3 text-xs"><span className="text-slate-400">{key}</span><b className="float-right">{value}</b></div>)}{Object.entries(data.statusCounts||{}).map(([key,value])=><div key={key} className="rounded-lg bg-slate-950 p-3 text-xs"><span className="text-slate-400">{key}</span><b className="float-right">{value}</b></div>)}</div>{data.totalIncidents===0&&<p className="mt-3 text-sm text-slate-400">No incident records were found in this five-year mine scope. No incident-based recommendations were generated.</p>}</section>
        <section className="rounded-2xl border border-violet-500/20 bg-violet-950/10 p-5"><h3 className="font-bold flex items-center gap-2"><Brain size={16} className="text-violet-300"/>AI risk estimate</h3>{data.ml?<><div className="mt-3 flex items-end gap-3"><strong className="text-4xl">{score??'—'}</strong><span className="mb-1 rounded-lg bg-violet-500/20 px-2 py-1 text-xs text-violet-200">{data.ml.riskLevel||'Unavailable'} risk</span></div><p className="mt-2 text-xs text-slate-300">{data.ml.anomalyStatus||'Anomaly assessment not returned'}</p>{data.ml.riskFactors?.length>0&&<ul className="mt-3 list-disc space-y-1 pl-5 text-xs text-slate-300">{data.ml.riskFactors.map((factor,i)=><li key={i}>{factor}</li>)}</ul>}<p className="mt-3 text-[10px] text-slate-400">{data.ml.datasetNotice}</p></>:<p className="mt-3 text-sm text-slate-400">{data.totalIncidents?data.mlUnavailable||'No ML result returned.':'No incident-based ML estimate is shown without historical records.'}</p>}</section></div>
      <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="font-bold flex items-center gap-2"><ShieldAlert size={16} className="text-amber-400"/>Suggested review actions</h3>{data.patterns?.length?<div className="mt-3 grid md:grid-cols-2 gap-3">{data.patterns.map((pattern,i)=><article key={i} className="rounded-xl border border-slate-800 bg-slate-950 p-4"><h4 className="text-sm font-bold">{pattern.title}</h4><p className="mt-1 text-xs text-amber-200">Evidence: {pattern.evidence}</p><p className="mt-2 text-xs leading-relaxed text-slate-300">{pattern.suggestion}</p></article>)}</div>:<p className="mt-3 text-sm text-slate-400">No recommendations until historical incidents are recorded.</p>}</section>
      <p className="rounded-xl border border-slate-800 bg-slate-950 p-3 text-[10px] leading-relaxed text-slate-400">{data.modelDisclaimer}</p></>}
    {data?.persistenceNotice&&<p className="rounded-xl border border-amber-500/30 bg-amber-950/30 p-3 text-xs text-amber-100">{data.persistenceNotice}</p>}
  </div>
}
