import { apiFetch } from '../../services/apiUrl.js'
import { useCallback, useEffect, useState } from 'react'
import { MapPinned, Plus, RefreshCw, Save, Trash2 } from 'lucide-react'

const cls='w-full rounded-xl bg-slate-950 border border-slate-700 px-3 py-2.5 text-sm text-slate-100 outline-none focus:border-amber-500'
const colors={SAFE:'#34d399',RESTRICTED:'#f87171',DANGER:'#fb923c',EMERGENCY_EXIT:'#38bdf8'}
const token=()=>localStorage.getItem('mineguard_jwt_token')||''
export default function SupervisorMapManagement(){
 const [maps,setMaps]=useState([]),[selectedId,setSelectedId]=useState(''),[scope,setScope]=useState(''),[name,setName]=useState(''),[zones,setZones]=useState([]),[selectedZone,setSelectedZone]=useState(''),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const selected=maps.find(m=>m._id===selectedId)
 const request=async(url,options={})=>{const res=await apiFetch(url,{...options,headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json',...options.headers}});const data=await res.json();if(!res.ok)throw new Error(data.message||'Map request failed');return data}
 const load=useCallback(async()=>{setLoading(true);setError('');try{const data=await request('/api/supervisor/maps');setMaps(data.maps||[]);setScope(data.mineScope||'');if(data.maps?.length&&!selectedId){const map=data.maps[0];setSelectedId(map._id);setName(map.name);setZones(map.zones||[]);setSelectedZone(map.zones?.[0]?.zoneId||'')}}catch(e){setError(e.message)}finally{setLoading(false)}},[selectedId])
 useEffect(()=>{load()},[load])
 const choose=id=>{setSelectedId(id);const map=maps.find(m=>m._id===id);if(map){setName(map.name);setZones(map.zones||[]);setSelectedZone(map.zones?.[0]?.zoneId||'')}else if(!id){setName('');setZones([]);setSelectedZone('')}}
 const updateZone=(id,field,value)=>setZones(current=>current.map(z=>z.zoneId===id?{...z,[field]:value}:z))
 const addZone=()=>{const id=`zone-${Date.now().toString(36)}`;setZones(current=>[...current,{zoneId:id,name:'New zone',type:'SAFE',coordinates:{x:50,y:50}}]);setSelectedZone(id)}
 const save=async()=>{setSaving(true);setError('');setMessage('');try{const body={name,zones};const result=selectedId?await request(`/api/supervisor/maps/${selectedId}`,{method:'PUT',body:JSON.stringify(body)}):await request('/api/supervisor/maps',{method:'POST',body:JSON.stringify(body)});setMessage('Mine map saved.');const data=await request('/api/supervisor/maps');setMaps(data.maps||[]);if(result.map?._id){setSelectedId(result.map._id);setName(result.map.name);setZones(result.map.zones||[])}}catch(e){setError(e.message)}finally{setSaving(false)}}
 const placePoint=e=>{if(!selectedZone)return;const rect=e.currentTarget.getBoundingClientRect();const x=Math.round(Math.max(0,Math.min(100,(e.clientX-rect.left)/rect.width*100)));const y=Math.round(Math.max(0,Math.min(100,(e.clientY-rect.top)/rect.height*100)));setZones(current=>current.map(z=>z.zoneId===selectedZone?{...z,coordinates:{...z.coordinates,x,y}}:z))}
 return <div className="p-4 sm:p-6 max-w-7xl mx-auto space-y-5 text-slate-100"><header className="flex flex-wrap justify-between items-center gap-3"><div><h2 className="text-2xl font-black flex items-center gap-2"><MapPinned className="text-amber-400"/>Mine Map Management</h2><p className="text-sm text-slate-400">Edit your authorized mine map and place zones by clicking the canvas.</p></div><button onClick={load} className="rounded-xl bg-slate-800 px-3 py-2 text-xs"><RefreshCw size={14} className={`inline mr-1 ${loading?'animate-spin':''}`}/>Refresh</button></header>
 {error&&<p className="rounded-xl border border-red-500/30 bg-red-950/40 p-3 text-sm text-red-200">{error}</p>}{message&&<p className="rounded-xl border border-emerald-500/30 bg-emerald-950/30 p-3 text-sm text-emerald-200">{message}</p>}
 <div className="grid lg:grid-cols-[minmax(0,1.4fr)_minmax(300px,0.8fr)] gap-4"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-4 space-y-3"><div className="flex flex-wrap gap-2"><select className={`${cls} flex-1`} value={selectedId} onChange={e=>choose(e.target.value)}><option value="">{maps.length?'Create or select a mine map':'Create a mine map'}</option>{maps.map(m=><option key={m._id} value={m._id}>{m.name} · {m.mineId}</option>)}</select><button onClick={()=>{setSelectedId('');setName(scope?`${scope} Map`:'Mine Map');setZones([]);setSelectedZone('')}} className="rounded-xl bg-slate-800 px-3 text-xs"><Plus size={14} className="inline mr-1"/>New map</button></div>
 <div className="relative aspect-[1.5] overflow-hidden rounded-xl border border-slate-700 bg-slate-950"><svg viewBox="0 0 100 100" className="h-full w-full cursor-crosshair" onClick={placePoint}><defs><pattern id="map-grid" width="10" height="10" patternUnits="userSpaceOnUse"><path d="M 10 0 L 0 0 0 10" fill="none" stroke="#1e293b" strokeWidth=".35"/></pattern></defs><rect width="100" height="100" fill="url(#map-grid)"/><path d="M8 75 C22 68,24 51,39 52 S56 58,64 38 S78 32,93 18" fill="none" stroke="#64748b" strokeWidth="2.5" strokeDasharray="2 1"/><text x="5" y="92" fill="#94a3b8" fontSize="3">Mine map layout · schematic coordinates</text>{zones.map(z=><g key={z.zoneId} transform={`translate(${Number(z.coordinates?.x)||0} ${Number(z.coordinates?.y)||0})`}><circle r={selectedZone===z.zoneId?3.5:2.5} fill={colors[z.type]||'#fbbf24'} stroke="#020617" strokeWidth=".8"/><text x="3.5" y="1" fill={colors[z.type]||'#fbbf24'} fontSize="3.2">{z.name}</text></g>)}</svg><div className="absolute left-2 top-2 rounded bg-black/70 px-2 py-1 text-[10px] text-slate-300">Click to place selected zone</div></div><p className="text-[10px] text-slate-400">This project’s map canvas is schematic. X/Y edits update the mine layout and do not represent GPS coordinates.</p></section>
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4 space-y-3"><label className="block text-xs text-slate-400">Map name<input className={`${cls} mt-1`} value={name} onChange={e=>setName(e.target.value)} maxLength={160}/></label><div className="flex items-center justify-between"><h3 className="font-bold text-sm">Configured zones ({zones.length})</h3><button onClick={addZone} className="rounded-lg bg-slate-800 px-2 py-1 text-xs"><Plus size={12} className="inline"/> Add zone</button></div><div className="max-h-[420px] overflow-y-auto space-y-2">{zones.map(z=><div key={z.zoneId} onClick={()=>setSelectedZone(z.zoneId)} className={`rounded-xl border p-3 space-y-2 ${selectedZone===z.zoneId?'border-amber-500/50 bg-slate-950':'border-slate-800 bg-slate-950/50'}`}><div className="flex gap-2"><input aria-label="Zone name" className={cls} value={z.name} onChange={e=>updateZone(z.zoneId,'name',e.target.value)} maxLength={100}/><button aria-label="Remove zone" onClick={()=>{setZones(prev=>prev.filter(row=>row.zoneId!==z.zoneId));if(selectedZone===z.zoneId)setSelectedZone('')}} className="rounded-lg bg-red-950 px-2 text-red-300"><Trash2 size={14}/></button></div><div className="grid grid-cols-3 gap-2"><select className={cls} value={z.type} onChange={e=>updateZone(z.zoneId,'type',e.target.value)}>{Object.keys(colors).map(t=><option key={t}>{t}</option>)}</select><label className="text-[10px] text-slate-400">X<input className={`${cls} mt-1`} type="number" min="0" max="100" value={z.coordinates?.x??0} onChange={e=>setZones(prev=>prev.map(row=>row.zoneId===z.zoneId?{...row,coordinates:{...row.coordinates,x:Number(e.target.value)}}:row))}/></label><label className="text-[10px] text-slate-400">Y<input className={`${cls} mt-1`} type="number" min="0" max="100" value={z.coordinates?.y??0} onChange={e=>setZones(prev=>prev.map(row=>row.zoneId===z.zoneId?{...row,coordinates:{...row.coordinates,y:Number(e.target.value)}}:row))}/></label></div><p className="text-[9px] text-slate-400">Zone ID: {z.zoneId}</p></div>)}{!zones.length&&<p className="rounded-xl border border-dashed border-slate-700 p-5 text-center text-xs text-slate-400">Add a zone, then click the map to place it.</p>}</div><button disabled={saving||!name.trim()} onClick={save} className="w-full rounded-xl bg-amber-500 py-2.5 font-black text-sm text-slate-950 disabled:grayscale disabled:cursor-not-allowed"><Save size={15} className="inline mr-2"/>{saving?'Saving…':'Save mine map'}</button></section></div>
 </div>
}
