import { useEffect, useRef, useState } from 'react'
import { Camera, ImagePlus, Loader2, ScanEye, X, Send } from 'lucide-react'

const token=()=>localStorage.getItem('mineguard_jwt_token')||''
export default function WorkerSafetyVision(){
 const [photo,setPhoto]=useState(null),[question,setQuestion]=useState(''),[analysis,setAnalysis]=useState(''),[disclaimer,setDisclaimer]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState(''),[configured,setConfigured]=useState(null),[busy,setBusy]=useState(false);const inputRef=useRef(null)
 useEffect(()=>{fetch('/api/labour/ai/status',{headers:{Authorization:`Bearer ${token()}`}}).then(r=>r.json()).then(d=>setConfigured(Boolean(d.configured))).catch(()=>setConfigured(false))},[])
 const selectFile=file=>{setError('');setAnalysis('');if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Choose a JPEG, PNG, or WebP photo.');return}if(file.size>4*1024*1024){setError('Photo must be 4 MB or smaller.');return}const reader=new FileReader();reader.onerror=()=>setError('Could not read this photo.');reader.onload=()=>setPhoto({name:file.name,mimeType:file.type,data:String(reader.result).split(',')[1],preview:String(reader.result)});reader.readAsDataURL(file)}
 const inspect=async()=>{if(!photo){setError('Capture or choose a photo first.');return}setBusy(true);setError('');setAnalysis('');try{const res=await fetch('/api/labour/ai/inspect',{method:'POST',headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:JSON.stringify({photo:{name:photo.name,mimeType:photo.mimeType,data:photo.data},question})});const data=await res.json();if(!res.ok)throw new Error(data.message||'AI inspection failed');setAnalysis(data.analysis);setDisclaimer(data.disclaimer)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const sendToSupervisor=async()=>{if(!photo)return;setBusy(true);setError('');setSuccess('');try{const res=await fetch('/api/labour/concerns',{method:'POST',headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:JSON.stringify({type:'SAFETY_ISSUE',title:'Photo safety concern',message:question.trim()||'Please review this mine-site photo for a possible safety concern.',photo:{name:photo.name,mimeType:photo.mimeType,data:photo.data}})});const data=await res.json();if(!res.ok)throw new Error(data.message||'Could not send the concern');setSuccess(data.persisted===false?'Sent to supervisor for review (temporary local storage; database is offline).':'Photo concern sent to your supervisor.');}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="space-y-4"><header><h2 className="text-lg font-black flex items-center gap-2"><ScanEye className="text-amber-400"/>AI Safety Photo Check</h2><p className="text-xs text-slate-400 mt-1">Take or choose a mine-site photo and ask MineGuard to flag visible potential hazards.</p></header>
  {configured===false&&<section className="rounded-xl border border-amber-500/30 bg-amber-950/30 p-3 text-xs text-amber-100"><strong>AI provider not connected.</strong> Add <code>GOOGLE_API_KEY</code> (Gemini) or <code>OPENAI_API_KEY</code> to the backend <code>.env</code> file, then restart <code>node server.js</code>. Keep the key on the backend; never put it in the browser app. You can still send a photo to your supervisor below.</section>}
  <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4 space-y-3"><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" capture="environment" className="hidden" onChange={e=>selectFile(e.target.files?.[0])}/><div className="flex gap-2"><button onClick={()=>inputRef.current?.click()} className="flex-1 rounded-xl bg-amber-500 px-3 py-3 text-xs font-black text-slate-950"><Camera size={15} className="inline mr-2"/>Take photo</button><button onClick={()=>inputRef.current?.click()} className="rounded-xl bg-slate-800 px-3 py-3 text-xs font-semibold"><ImagePlus size={15} className="inline mr-1"/>Gallery</button></div>
   {photo&&<div className="relative"><img src={photo.preview} alt="Photo selected for AI safety check" className="max-h-72 w-full rounded-xl border border-slate-700 object-contain bg-black"/><button onClick={()=>setPhoto(null)} aria-label="Remove photo" className="absolute right-2 top-2 rounded-full bg-black/80 p-2"><X size={15}/></button><p className="mt-1 text-[10px] text-slate-500">{photo.name}</p></div>}
   <textarea value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1000} rows={2} className="w-full rounded-xl bg-slate-950 border border-slate-700 p-3 text-sm text-slate-100" placeholder="Optional: What should I check in this photo?"/>
   <p className="text-[10px] text-slate-500">When configured, the photo and question are sent to MineGuard’s AI provider for analysis. Avoid photographing faces or personal documents. Analysis can miss hazards; follow site procedures.</p>
   <button disabled={!photo||busy} onClick={inspect} className="w-full rounded-xl bg-amber-500 py-3 text-sm font-black text-slate-950 disabled:opacity-50">{busy?<><Loader2 size={15} className="inline mr-2 animate-spin"/>Checking photo…</>:<><ScanEye size={15} className="inline mr-2"/>Check for visible hazards</>}</button>
   {(configured===false||(error&&photo))&&<button disabled={!photo||busy} onClick={sendToSupervisor} className="w-full rounded-xl border border-sky-500/40 bg-sky-950/50 py-3 text-sm font-bold text-sky-100 disabled:opacity-50">{busy?'Sending…':<><Send size={15} className="inline mr-2"/>Send photo concern to supervisor</>}</button>}
  </section>{error&&<div className="rounded-xl border border-red-500/30 bg-red-950/40 p-3 text-xs text-red-200">{error}</div>}{success&&<div className="rounded-xl border border-emerald-500/30 bg-emerald-950/40 p-3 text-xs text-emerald-100">{success}</div>}{analysis&&<section className="rounded-2xl border border-amber-500/30 bg-slate-900 p-4"><h3 className="font-bold text-amber-200">AI visual review</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-slate-200">{analysis}</p><p className="mt-3 text-[10px] text-slate-500">{disclaimer}</p></section>}</div>
}
