import { useEffect, useRef, useState } from 'react'
import { Bot, Loader2, Send, ShieldAlert, Trash2 } from 'lucide-react'

const token=()=>localStorage.getItem('mineguard_jwt_token')||''
export default function WorkerAIAssistant(){
 const [messages,setMessages]=useState([]),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[configured,setConfigured]=useState(null);const bottomRef=useRef(null)
 useEffect(()=>{fetch('/api/labour/ai/status',{headers:{Authorization:`Bearer ${token()}`}}).then(r=>r.json()).then(d=>setConfigured(Boolean(d.configured))).catch(()=>setConfigured(false))},[])
 const send=async(text=draft)=>{const question=text.trim();if(!question||busy)return;const next=[...messages,{role:'user',content:question}].slice(-8);setMessages(next);setDraft('');setError('');setBusy(true);try{const res=await fetch('/api/labour/ai/ask',{method:'POST',headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'},body:JSON.stringify({messages:next})});const data=await res.json();if(!res.ok)throw new Error(data.message||'Assistant is unavailable');setMessages(current=>[...current,{role:'assistant',content:data.answer,disclaimer:data.disclaimer}].slice(-10));setTimeout(()=>bottomRef.current?.scrollIntoView({behavior:'smooth'}),50)}catch(e){setMessages(current=>current.slice(0,-1));setDraft(question);setError(e.message)}finally{setBusy(false)}}
 return <div className="space-y-4"><header><h2 className="text-lg font-black flex items-center gap-2"><Bot className="text-sky-400"/>Ask MineGuard</h2><p className="mt-1 text-xs text-slate-400">Ask about general safety practices, understand a hazard, or get help writing a clear report.</p></header>
  {configured===false&&<div className="rounded-xl border border-amber-500/30 bg-amber-950/30 p-3 text-xs text-amber-100"><strong>AI assistant not connected.</strong> To enable it, add <code>GOOGLE_API_KEY</code> (Gemini) or <code>OPENAI_API_KEY</code> to the backend <code>.env</code> and restart <code>node server.js</code>. Do not put the key in frontend code or share it in chat. Use the supervisor concern/report section for urgent issues.</div>}
  <div className="flex flex-wrap gap-2">{['What should I do if I smell gas?','How do I report a damaged support?','Help me write a safety report'].map(s=><button key={s} disabled={busy} onClick={()=>send(s)} className="rounded-full border border-slate-700 bg-slate-900 px-3 py-2 text-[10px] text-slate-300">{s}</button>)}</div>
  <section className="min-h-64 rounded-2xl border border-slate-800 bg-slate-900 p-3 space-y-3">{!messages.length&&<div className="py-12 text-center text-xs text-slate-500"><Bot size={26} className="mx-auto mb-2 text-sky-400"/>Ask your question. If anything is immediately dangerous, stop work, move to safety if possible, alert a supervisor, or use the site SOS procedure.</div>}{messages.map((m,i)=><div key={i} className={`max-w-[90%] rounded-2xl p-3 text-xs leading-relaxed ${m.role==='user'?'ml-auto bg-amber-500 text-slate-950':'bg-slate-950 text-slate-200'}`}><p className="whitespace-pre-wrap">{m.content}</p>{m.disclaimer&&<p className="mt-2 text-[9px] text-slate-500">{m.disclaimer}</p>}</div>)}{busy&&<p className="text-xs text-slate-400"><Loader2 size={13} className="inline mr-1 animate-spin"/>MineGuard is thinking…</p>}<div ref={bottomRef}/></section>
  {error&&<div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-amber-500/30 bg-amber-950/30 p-3 text-xs text-amber-100"><span>{error}</span><button type="button" onClick={()=>send(draft)} disabled={busy||!draft.trim()} className="rounded-lg border border-amber-400/40 px-3 py-1.5 font-bold text-amber-200 disabled:opacity-50">Retry</button></div>}
  <form onSubmit={e=>{e.preventDefault();send()}} className="flex gap-2"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} maxLength={1200} rows={2} placeholder="Ask a safety question…" className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm text-slate-100"/><button disabled={!draft.trim()||busy} aria-label="Send question" className="rounded-xl bg-sky-500 px-4 text-slate-950 disabled:opacity-40"><Send size={17}/></button></form>
  <div className="flex items-start justify-between gap-2 rounded-xl border border-red-500/20 bg-red-950/20 p-3 text-[10px] text-slate-400"><ShieldAlert size={14} className="shrink-0 text-red-300"/>AI guidance may be wrong and is not an emergency response, medical diagnosis, or official mine instruction. Follow your site procedures and supervisor direction.<button onClick={()=>{setMessages([]);setError('')}} className="shrink-0 text-slate-400" aria-label="Clear chat"><Trash2 size={13}/></button></div>
 </div>
}
